title: Articles
author: "Yuriy Lozhkin"
timezone: Etc/UTC
url: ""
baseurl: "/articles"
markdown: kramdown

# Build settings
safe: true

# Syntax highlighting with Rouge (GitHub Pages supports Rouge)
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: false

# Optional: set defaults for posts if you want
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
