title: Articles
author: "Yuriy Lozhkin"
timezone: Etc/UTC
url: ""
baseurl: "/articles"
markdown: kramdown

# Build settings
safe: true

# Optional: set defaults for posts if you want
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
